### ISSUE TITLE
LogIn with API

### ISSUE THREAD

**Issue by steevivo** [q1x/zabbix-gnomes#10]
Hi,

Since few days , I have a strange error with login API :
Traceback (most recent call last):
  File "./zhostfinder.py", line 114, in <module>
    zapi.login(username, password)
TypeError: 'ZabbixAPIObjectClass' object is not callable

Any Ideas ?
Thx

**Comment by steevivo** [comment]
It's ok now

**Comment by q1x** [comment]
Hi Stephane,

Can you share what the problem was?

**Comment by steevivo** [comment]
Hi Raymond,

In fact I think this is not a good way but for my test I modify this line :

```
# Login to the Zabbix API
zapi.login(username, password)

By this 
#zapi.login(username, password)
```
And it's running.... I use zabbix 4.2.1 and I don't know if it's an API problem or not

**Comment by q1x** [comment]
Hi Stephane,

I just checked on a fresh Centos7 install with Zabbix 4.0.9, no issues there as far as I can see right now.
Did you use a configuration file or did you pass api parameters on the cli as arguments?

Regards,

Raymond

**Comment by steevivo** [comment]
Raymond ,
Yes I use it with .zbx.conf , this is why I have the message I think so , sorry about that

Regards
Stephane

**Comment by q1x** [comment]
Ok, is this with all scripts or just with a specific one?

**Comment by steevivo** [comment]
For All scripts

**Comment by q1x** [comment]
which version of pyzabbix are you using?

**Comment by steevivo** [comment]
pyzabbix 0.7.5

**Comment by herdir** [comment]
Same issue with pyzabbix Version: 1.0.0
using Python 2.7.18

`Traceback (most recent call last):
  File "./zhostupdater.py", line 126, in <module>
    zapi.login(username, password)
TypeError: 'ZabbixAPIObjectClass' object is not callable`

Same issue using Python 3.9.2 and pyzabbix Version: 1.0.0
